// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jcsbjhrnyudcoihikkzo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impjc2JqaHJueXVkY29paGlra3pvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxOTA5NDMsImV4cCI6MjA2OTc2Njk0M30.YWdNl-So8fF-Rze8anuNWvLNHub2PZ5erQqV9lz7mHY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});